### ISSUE TITLE
autorefresh

### ISSUE THREAD

**Issue by quaso** [IgorKvasn/swiss-frontend#3]

**Comment by IgorKvasn** [comment]
@quaso  autorefresh by mal fungovat - mas nejaky use case, kedy nefunguje? kazdych 5 min to checkuje, ci nedoslo k zmenam a potom v hornom navbare o tom vypise hlasku - klinutim na hlasku sa zmena aplikuje

**Comment by quaso** [comment]
netestoval som :}

**Comment by quaso** [comment]
GET /tournaments/{id} = Tournament.TournamentSettings.lastUpdated

**Comment by IgorKvasn** [comment]
neviem, ci tam je ten lastUpdated treba - robim to velmi drevorubacsky, ze to, co mi server kedysi poslal porovnam s tym, co mi prave teraz poslal - ak je to ine, tak to znamena, ze sa tam nieco zmenilo.... je to strasne primitivny sposob, ale funguje....

**Comment by quaso** [comment]
mozes vypisovat, kedy to bolo zmenene :)
